import type { Locale } from '@/i18n/routing';

// ── What's New / changelog ────────────────────────────────────────────────────
//
// The single source of truth for the in-app "What's New" panel (sidebar button
// + modal). Entries live in the repo — not the database — deliberately: a
// release note belongs to the commit that shipped the feature, so whoever
// (human or agent) builds something user-visible adds its line here in the same
// change. No migration, no admin CMS, no drift between what shipped and what
// the panel claims.
//
// Writing rules (see CLAUDE.md / AI.md "After a meaningful change"):
//   • One entry per user-visible improvement. Skip refactors, internal scripts,
//     docs-only churn and anything a customer would never notice.
//   • `summary` is exactly ONE sentence. No paragraphs, no bullet lists.
//   • Customer language, not engineering language: say what they can now do,
//     never which table/component/endpoint changed.
//   • Small changes still get written up so they read as worth reading.
//   • Newest entry goes FIRST in the array.
//   • All 8 locales are required — `Record<Locale, string>` makes `tsc` fail
//     on a missing one, so the panel can never fall back to English silently.

export type ChangelogCategory = 'new' | 'improved' | 'fixed';

export type LocalizedText = Record<Locale, string>;

export interface ChangelogEntry {
  /** Stable slug, `YYYY-MM-DD-kebab-topic`. Never reuse or rewrite a shipped id — the
   *  "seen" cookie stores it, and changing it re-flags the entry as unread for everyone. */
  id: string;
  /** Ship date, `YYYY-MM-DD`. Groups the cards in the modal. */
  date: string;
  category: ChangelogCategory;
  title: LocalizedText;
  /** Exactly one sentence. */
  summary: LocalizedText;
}

/** Client-readable cookie holding the id of the newest entry the user has seen. */
export const CHANGELOG_SEEN_COOKIE = 'remnus_whatsnew_seen';

/** A brand-new account has no cookie; only entries this fresh count as unread for
 *  them, so signing up never greets you with a "24 updates" badge. */
const FIRST_VISIT_WINDOW_DAYS = 7;

export const CHANGELOG: ChangelogEntry[] = [
  {
    id: '2026-09-23-agent-status-options',
    date: '2026-09-23',
    category: 'fixed',
    title: {
      en: 'Agent-made status columns keep their names',
      tr: 'Ajanın oluşturduğu durum kolonları adlarını koruyor',
      de: 'Statusspalten von Agenten behalten ihre Namen',
      es: 'Las columnas de estado de los agentes conservan sus nombres',
      fr: 'Les colonnes de statut créées par un agent gardent leurs noms',
      hi: 'एजेंट के बनाए स्टेटस कॉलम अपने नाम बनाए रखते हैं',
      ru: 'Столбцы статуса от агента сохраняют названия',
      zh: '智能体创建的状态列会保留选项名称',
    },
    summary: {
      en: 'Status and select columns an AI agent creates now keep their option names even when the agent describes them the way Notion does, instead of showing "[object Object]".',
      tr: 'Bir yapay zekâ ajanının oluşturduğu durum ve seçim kolonları, ajan seçenekleri Notion\'daki gibi tarif etse bile artık "[object Object]" yerine seçenek adlarını koruyor.',
      de: 'Status- und Auswahlspalten, die ein KI-Agent anlegt, behalten jetzt ihre Optionsnamen, auch wenn der Agent sie wie in Notion beschreibt, statt „[object Object]“ anzuzeigen.',
      es: 'Las columnas de estado y selección que crea un agente de IA ahora conservan los nombres de sus opciones aunque el agente las describa como en Notion, en lugar de mostrar "[object Object]".',
      fr: 'Les colonnes de statut et de sélection créées par un agent IA gardent désormais le nom de leurs options, même décrites à la manière de Notion, au lieu d\'afficher « [object Object] ».',
      hi: 'किसी AI एजेंट के बनाए स्टेटस और सेलेक्ट कॉलम अब अपने विकल्पों के नाम बनाए रखते हैं, भले ही एजेंट उन्हें Notion की तरह बताए, "[object Object]" दिखाने के बजाय।',
      ru: 'Столбцы статуса и выбора, созданные ИИ-агентом, теперь сохраняют названия вариантов, даже если агент описывает их как в Notion, вместо «[object Object]».',
      zh: 'AI 智能体创建的状态列和选择列现在会保留选项名称，即使它按 Notion 的方式描述选项，也不再显示 "[object Object]"。',
    },
  },
  {
    id: '2026-09-23-wiki-markdown',
    date: '2026-09-23',
    category: 'improved',
    title: {
      en: 'Wiki pages your agent can read whole',
      tr: 'Ajanınızın eksiksiz okuyabildiği wiki sayfaları',
      de: 'Wiki-Seiten, die Ihr Agent vollständig liest',
      es: 'Páginas de la wiki que tu agente lee completas',
      fr: 'Des pages wiki que votre agent lit en entier',
      hi: 'विकी पेज जिन्हें आपका एजेंट पूरा पढ़ सकता है',
      ru: 'Страницы вики, которые агент читает целиком',
      zh: '智能体可完整读取的 Wiki 页面',
    },
    summary: {
      en: 'Add .md to any wiki address to get the page as plain markdown, which is what npx remnus init now hands your agent, so it follows the setup guide in full for a fraction of the tokens.',
      tr: 'Herhangi bir wiki adresinin sonuna .md eklediğinizde sayfayı düz markdown olarak alırsınız; npx remnus init artık ajanınıza bu adresi veriyor, böylece ajan kurulum rehberini çok daha az token harcayarak eksiksiz uyguluyor.',
      de: 'Hängen Sie .md an eine Wiki-Adresse an, um die Seite als reines Markdown zu erhalten – genau das gibt npx remnus init Ihrem Agenten jetzt mit, sodass er die Einrichtungsanleitung vollständig und mit einem Bruchteil der Tokens befolgt.',
      es: 'Añade .md a cualquier dirección de la wiki para obtener la página en markdown plano, que es lo que npx remnus init entrega ahora a tu agente, para que siga la guía de configuración completa con una fracción de los tokens.',
      fr: 'Ajoutez .md à n\'importe quelle adresse du wiki pour obtenir la page en markdown brut, ce que npx remnus init donne désormais à votre agent, qui suit ainsi le guide de configuration en entier pour une fraction des tokens.',
      hi: 'किसी भी विकी पते के अंत में .md जोड़ें और पेज सादे markdown में पाएँ — npx remnus init अब आपके एजेंट को यही पता देता है, ताकि वह बहुत कम टोकन में पूरी सेटअप गाइड का पालन करे।',
      ru: 'Добавьте .md к адресу любой страницы вики, чтобы получить её в виде чистого markdown, — именно этот адрес теперь передаёт агенту npx remnus init, и он выполняет руководство по настройке целиком, тратя лишь малую долю токенов.',
      zh: '在任意 Wiki 地址后加上 .md 即可获取页面的纯 markdown 版本，npx remnus init 现在就把这个地址交给你的智能体，让它以极少的 token 完整遵循设置指南。',
    },
  },
  {
    id: '2026-09-23-audit-retention',
    date: '2026-09-23',
    category: 'improved',
    title: {
      en: 'Activity history that follows your plan',
      tr: 'Planınıza göre işleyen etkinlik geçmişi',
      de: 'Aktivitätsverlauf passend zu Ihrem Tarif',
      es: 'Historial de actividad según tu plan',
      fr: 'Un historique d\'activité adapté à votre offre',
      hi: 'आपके प्लान के अनुसार गतिविधि इतिहास',
      ru: 'История активности по вашему тарифу',
      zh: '按套餐保留的活动记录',
    },
    summary: {
      en: 'Your agents\' activity log now keeps the history your plan includes, from 7 days on Free up to a full year on Enterprise, and upgrading shows your older history right away.',
      tr: 'Ajanlarınızın etkinlik kaydı artık planınızın kapsadığı geçmişi tutuyor; Ücretsiz planda 7 günden Enterprise planda bir yıla kadar, ve planınızı yükselttiğinizde eski kayıtlarınız hemen görünür.',
      de: 'Das Aktivitätsprotokoll Ihrer Agenten umfasst jetzt den Verlauf, den Ihr Tarif enthält, von 7 Tagen im Free-Tarif bis zu einem ganzen Jahr bei Enterprise, und nach einem Upgrade sehen Sie Ihren älteren Verlauf sofort.',
      es: 'El registro de actividad de tus agentes ahora conserva el historial que incluye tu plan, desde 7 días en Free hasta un año completo en Enterprise, y al mejorar tu plan verás tu historial anterior al instante.',
      fr: 'Le journal d\'activité de vos agents conserve désormais l\'historique inclus dans votre offre, de 7 jours en Free jusqu\'à un an en Enterprise, et votre historique plus ancien réapparaît dès que vous passez à une offre supérieure.',
      hi: 'आपके एजेंटों का गतिविधि लॉग अब उतना इतिहास रखता है जितना आपके प्लान में शामिल है, Free पर 7 दिन से लेकर Enterprise पर पूरे एक साल तक, और प्लान अपग्रेड करते ही आपका पुराना इतिहास तुरंत दिखने लगता है।',
      ru: 'Журнал активности ваших агентов теперь хранит историю, которую включает ваш тариф, от 7 дней на Free до целого года на Enterprise, а после перехода на более высокий тариф старые записи сразу снова видны.',
      zh: '智能体的活动日志现在会保留你的套餐所包含的历史记录，从免费版的 7 天到企业版的整整一年，升级套餐后更早的记录会立即重新显示。',
    },
  },
  {
    id: '2026-09-23-calibration-playbooks',
    date: '2026-09-23',
    category: 'new',
    title: {
      en: 'Setup that knows your kind of project',
      tr: 'Proje türünüzü tanıyan kurulum',
      de: 'Einrichtung, die Ihre Projektart kennt',
      es: 'Una configuración que conoce tu tipo de proyecto',
      fr: 'Une configuration qui connaît votre type de projet',
      hi: 'ऐसा सेटअप जो आपके प्रोजेक्ट का प्रकार पहचानता है',
      ru: 'Настройка, которая знает ваш тип проекта',
      zh: '懂你项目类型的初始设置',
    },
    summary: {
      en: 'When an agent sets up your workspace for a web app, an API, a game, a data project or a library, it now tracks what that kind of project actually needs, and the new Playbooks page shows you exactly what it will build.',
      tr: 'Bir ajan çalışma alanınızı bir web uygulaması, API, oyun, veri projesi ya da kütüphane için kurarken artık o tür projenin gerçekten ihtiyaç duyduğu şeyleri takip ediyor; yeni Playbooks sayfası da neyi kuracağını size tam olarak gösteriyor.',
      de: 'Wenn ein Agent Ihren Workspace für eine Web-App, eine API, ein Spiel, ein Datenprojekt oder eine Bibliothek einrichtet, bildet er jetzt ab, was diese Art von Projekt wirklich braucht, und die neue Playbooks-Seite zeigt Ihnen genau, was er aufbauen wird.',
      es: 'Cuando un agente configura tu espacio de trabajo para una aplicación web, una API, un juego, un proyecto de datos o una librería, ahora organiza lo que ese tipo de proyecto realmente necesita, y la nueva página Playbooks te muestra exactamente lo que va a crear.',
      fr: 'Quand un agent configure votre espace de travail pour une application web, une API, un jeu, un projet de données ou une bibliothèque, il suit désormais ce dont ce type de projet a réellement besoin, et la nouvelle page Playbooks vous montre précisément ce qu\'il va créer.',
      hi: 'जब कोई एजेंट आपके वर्कस्पेस को किसी वेब ऐप, API, गेम, डेटा प्रोजेक्ट या लाइब्रेरी के लिए सेट करता है, तो अब वह वही चीज़ें ट्रैक करता है जिनकी उस तरह के प्रोजेक्ट को सच में ज़रूरत होती है, और नया Playbooks पेज आपको ठीक-ठीक दिखाता है कि वह क्या बनाएगा।',
      ru: 'Когда агент настраивает рабочее пространство под веб-приложение, API, игру, проект с данными или библиотеку, он теперь заводит именно то, что нужно такому проекту, а новая страница Playbooks заранее показывает, что именно он создаст.',
      zh: '当智能体为 Web 应用、API、游戏、数据项目或代码库设置你的工作区时，它现在会搭建这类项目真正需要跟踪的内容，新的 Playbooks 页面也会提前告诉你它将创建什么。',
    },
  },
  {
    id: '2026-09-23-calibration-log',
    date: '2026-09-23',
    category: 'improved',
    title: {
      en: 'Watch your workspace setup take shape',
      tr: 'Çalışma alanı kurulumunu adım adım izleyin',
      de: 'Sehen Sie zu, wie Ihr Workspace entsteht',
      es: 'Mira cómo toma forma la configuración de tu espacio',
      fr: 'Suivez la mise en place de votre espace de travail',
      hi: 'अपने वर्कस्पेस का सेटअप बनते हुए देखें',
      ru: 'Наблюдайте, как настраивается рабочее пространство',
      zh: '看着工作区一步步搭建起来',
    },
    summary: {
      en: 'When an agent sets up your workspace for a project, it now writes its plan to a Calibration Log page before building anything, picks up where it left off if interrupted, and adds a status dashboard wherever your project has progress to track.',
      tr: 'Bir ajan çalışma alanınızı bir proje için kurarken artık hiçbir şey oluşturmadan önce planını bir Calibration Log sayfasına yazıyor, yarıda kalırsa kaldığı yerden devam ediyor ve projenizde takip edilecek bir ilerleme varsa bir durum panosu da ekliyor.',
      de: 'Wenn ein Agent Ihren Workspace für ein Projekt einrichtet, schreibt er jetzt seinen Plan auf eine Calibration-Log-Seite, bevor er etwas anlegt, macht nach einer Unterbrechung dort weiter, wo er aufgehört hat, und ergänzt ein Status-Dashboard, wo es in Ihrem Projekt Fortschritt zu verfolgen gibt.',
      es: 'Cuando un agente configura tu espacio de trabajo para un proyecto, ahora escribe su plan en una página Calibration Log antes de crear nada, continúa donde lo dejó si se interrumpe y añade un panel de estado cuando tu proyecto tiene avances que seguir.',
      fr: 'Quand un agent configure votre espace de travail pour un projet, il écrit désormais son plan dans une page Calibration Log avant de créer quoi que ce soit, reprend là où il s\'était arrêté en cas d\'interruption et ajoute un tableau de bord de suivi dès que votre projet a une progression à suivre.',
      hi: 'जब कोई एजेंट किसी प्रोजेक्ट के लिए आपका वर्कस्पेस सेट करता है, तो अब वह कुछ भी बनाने से पहले अपनी योजना एक Calibration Log पेज पर लिखता है, रुकावट आने पर वहीं से आगे बढ़ता है जहाँ रुका था, और जहाँ आपके प्रोजेक्ट में ट्रैक करने लायक प्रगति हो वहाँ एक स्टेटस डैशबोर्ड भी जोड़ता है।',
      ru: 'Когда агент настраивает рабочее пространство под проект, он теперь сначала записывает план на страницу Calibration Log, после прерывания продолжает с того же места и добавляет дашборд статуса, если в проекте есть прогресс, за которым стоит следить.',
      zh: '当智能体为某个项目设置你的工作区时，它现在会先把计划写进一个 Calibration Log 页面再动手搭建，中途被打断也能从上次停下的地方继续，并在你的项目有进度需要跟踪时加上一个状态仪表板。',
    },
  },
  {
    id: '2026-09-23-agent-built-dashboards',
    date: '2026-09-23',
    category: 'new',
    title: {
      en: 'Your agent builds dashboards, you fine-tune them',
      tr: 'Panoyu ajanınız kurar, siz ince ayarını yaparsınız',
      de: 'Ihr Agent baut Dashboards, Sie feilen daran',
      es: 'Tu agente crea paneles y tú los ajustas',
      fr: 'Votre agent crée les tableaux de bord, vous les peaufinez',
      hi: 'आपका एजेंट डैशबोर्ड बनाता है, आप उसे निखारते हैं',
      ru: 'Агент собирает дашборды, а вы их донастраиваете',
      zh: '智能体搭建仪表板，你来微调',
    },
    summary: {
      en: 'Ask your AI agent for a status dashboard and it builds and updates one straight from your databases, while you can add blocks and change any block\'s settings yourself right on the page.',
      tr: 'Yapay zekâ ajanınızdan bir durum panosu isteyin, doğrudan veritabanlarınızdan kurup güncellesin; siz de sayfanın üzerinden blok ekleyip her bloğun ayarlarını kendiniz değiştirebilirsiniz.',
      de: 'Bitten Sie Ihren KI-Agenten um ein Status-Dashboard, und er baut und aktualisiert es direkt aus Ihren Datenbanken, während Sie selbst auf der Seite Blöcke hinzufügen und die Einstellungen jedes Blocks ändern können.',
      es: 'Pide a tu agente de IA un panel de estado y lo crea y actualiza directamente a partir de tus bases de datos, mientras tú puedes añadir bloques y cambiar los ajustes de cualquiera desde la propia página.',
      fr: 'Demandez un tableau de bord de suivi à votre agent IA et il le construit et le met à jour directement à partir de vos bases de données, tandis que vous pouvez ajouter des blocs et modifier les réglages de chacun depuis la page.',
      hi: 'अपने AI एजेंट से एक स्टेटस डैशबोर्ड माँगें और वह उसे सीधे आपके डेटाबेस से बनाकर अपडेट करता है, जबकि आप खुद पेज पर ही ब्लॉक जोड़ सकते हैं और किसी भी ब्लॉक की सेटिंग्स बदल सकते हैं।',
      ru: 'Попросите ИИ-агента сделать дашборд статуса — он соберёт и будет обновлять его прямо по вашим базам данных, а вы сами можете добавлять блоки и менять настройки любого из них прямо на странице.',
      zh: '让你的 AI 智能体做一个状态仪表板，它会直接基于你的数据库搭建并持续更新，而你也可以在页面上自己添加区块、修改任意区块的设置。',
    },
  },
  {
    id: '2026-09-22-dashboards',
    date: '2026-09-22',
    category: 'new',
    title: {
      en: 'Dashboards that read your own data',
      tr: 'Kendi verinizi okuyan panolar',
      de: 'Dashboards, die Ihre eigenen Daten lesen',
      es: 'Paneles que leen tus propios datos',
      fr: 'Des tableaux de bord qui lisent vos propres données',
      hi: 'आपका डेटा पढ़ने वाले डैशबोर्ड',
      ru: 'Дашборды, которые читают ваши данные',
      zh: '能读你自己数据的仪表板',
    },
    summary: {
      en: 'You can now add a dashboard next to your pages and databases and ask your AI agent to fill it with live numbers, charts and lists drawn straight from your own data.',
      tr: 'Artık sayfalarınızın ve veritabanlarınızın yanına bir pano ekleyip yapay zekâ ajanınızdan onu doğrudan kendi verinizden gelen canlı sayılar, grafikler ve listelerle doldurmasını isteyebilirsiniz.',
      de: 'Sie können jetzt neben Ihren Seiten und Datenbanken ein Dashboard anlegen und Ihren KI-Agenten bitten, es mit aktuellen Zahlen, Diagrammen und Listen direkt aus Ihren eigenen Daten zu füllen.',
      es: 'Ahora puedes añadir un panel junto a tus páginas y bases de datos y pedir a tu agente de IA que lo llene con cifras, gráficos y listas en vivo sacados de tus propios datos.',
      fr: 'Vous pouvez désormais ajouter un tableau de bord à côté de vos pages et bases de données et demander à votre agent IA de le remplir de chiffres, graphiques et listes en direct tirés de vos propres données.',
      hi: 'अब आप अपने पृष्ठों और डेटाबेस के साथ एक डैशबोर्ड जोड़कर अपने AI एजेंट से उसे आपके अपने डेटा से सीधे आए लाइव आँकड़ों, चार्ट और सूचियों से भरने को कह सकते हैं।',
      ru: 'Теперь рядом со страницами и базами данных можно добавить дашборд и попросить ИИ-агента заполнить его живыми цифрами, графиками и списками прямо из ваших данных.',
      zh: '现在你可以在页面和数据库旁边新建一个仪表板，让 AI 智能体用直接取自你自己数据的实时数字、图表和列表把它填满。',
    },
  },
  {
    id: '2026-09-22-see-what-your-agents-saved',
    date: '2026-09-22',
    category: 'new',
    title: {
      en: 'See what your agents saved you',
      tr: 'Ajanlarınızın size ne kazandırdığını görün',
      de: 'Sehen Sie, was Ihre Agenten gespart haben',
      es: 'Mira lo que te ahorraron tus agentes',
      fr: 'Voyez ce que vos agents vous ont économisé',
      hi: 'देखें कि आपके एजेंटों ने आपका क्या बचाया',
      ru: 'Посмотрите, что сэкономили ваши агенты',
      zh: '看看你的智能体为你省下了多少',
    },
    summary: {
      en: 'A counter at the bottom of the sidebar now shows how many tokens your agents did not have to spend, with a plain explanation behind every number.',
      tr: 'Kenar çubuğunun altındaki yeni sayaç, ajanlarınızın harcamak zorunda kalmadığı token miktarını her sayının nereden geldiğini açıklayarak gösteriyor.',
      de: 'Ein Zähler unten in der Seitenleiste zeigt jetzt, wie viele Tokens Ihre Agenten nicht ausgeben mussten — mit einer klaren Erklärung hinter jeder Zahl.',
      es: 'Un contador al final de la barra lateral muestra ahora cuántos tokens no tuvieron que gastar tus agentes, con una explicación clara detrás de cada cifra.',
      fr: 'Un compteur en bas de la barre latérale indique désormais combien de tokens vos agents n\'ont pas eu à dépenser, avec une explication claire derrière chaque chiffre.',
      hi: 'साइडबार के नीचे एक नया काउंटर दिखाता है कि आपके एजेंटों को कितने टोकन खर्च नहीं करने पड़े, और हर संख्या के पीछे की वजह भी बताता है।',
      ru: 'Счётчик внизу боковой панели теперь показывает, сколько токенов вашим агентам не пришлось потратить, и поясняет, откуда взялась каждая цифра.',
      zh: '侧边栏底部新增计数器，显示你的智能体省下的 token 数量，并说明每个数字的来历。',
    },
  },
  {
    id: '2026-09-22-agents-use-less-of-your-limit',
    date: '2026-09-22',
    category: 'improved',
    title: {
      en: 'Agents work faster and use less of your limit',
      tr: 'Ajanlar daha hızlı çalışıyor ve limitinizden daha az harcıyor',
      de: 'Agenten arbeiten schneller und verbrauchen weniger von Ihrem Limit',
      es: 'Los agentes trabajan más rápido y consumen menos de tu límite',
      fr: 'Les agents travaillent plus vite et consomment moins de votre quota',
      hi: 'एजेंट तेज़ी से काम करते हैं और आपकी सीमा कम खर्च करते हैं',
      ru: 'Агенты работают быстрее и расходуют меньше вашего лимита',
      zh: '智能体更快，也更省你的额度',
    },
    summary: {
      en: 'An agent connected to your workspace now starts each session already knowing what is where, so it spends far less of your usage limit finding things before it can help you.',
      tr: 'Çalışma alanınıza bağlı bir ajan artık her oturuma neyin nerede olduğunu bilerek başlıyor; size yardım edebilmek için önce etrafı aramaya kullanım limitinizden çok daha azını harcıyor.',
      de: 'Ein mit Ihrem Workspace verbundener Agent beginnt jede Sitzung nun mit dem Wissen, wo was liegt, und verbraucht so deutlich weniger Ihres Nutzungslimits, nur um sich zurechtzufinden.',
      es: 'Un agente conectado a tu espacio de trabajo ahora empieza cada sesión sabiendo ya dónde está cada cosa, así que gasta mucho menos de tu límite de uso buscando antes de poder ayudarte.',
      fr: 'Un agent connecté à votre espace de travail commence désormais chaque session en sachant déjà où se trouve quoi, et consomme donc bien moins de votre quota avant de pouvoir vous aider.',
      hi: 'आपके वर्कस्पेस से जुड़ा एजेंट अब हर सत्र की शुरुआत यह जानते हुए करता है कि क्या कहाँ है, इसलिए आपकी मदद शुरू करने से पहले चीज़ें ढूँढ़ने में आपकी उपयोग सीमा बहुत कम खर्च होती है।',
      ru: 'Агент, подключённый к вашему рабочему пространству, теперь начинает каждую сессию, уже зная, что где находится, и тратит заметно меньше вашего лимита на поиски, прежде чем взяться за дело.',
      zh: '连接到你工作区的智能体，现在每次开始时就已经知道什么放在哪里，因此在真正帮上忙之前，花在到处翻找上的额度大大减少。',
    },
  },
  {
    id: '2026-09-22-agent-pages-on-shared-sites',
    date: '2026-09-22',
    category: 'fixed',
    title: {
      en: 'Agent-written pages show up on your published site',
      tr: 'Ajanın yazdığı sayfalar yayınlanmış sitenizde görünüyor',
      de: 'Von Agenten erstellte Seiten erscheinen auf Ihrer veröffentlichten Website',
      es: 'Las páginas que escribe un agente aparecen en tu sitio publicado',
      fr: 'Les pages écrites par un agent apparaissent sur votre site publié',
      hi: 'एजेंट की लिखी पेज अब आपकी प्रकाशित साइट पर दिखती हैं',
      ru: 'Страницы, созданные агентом, появляются на опубликованном сайте',
      zh: '智能体创建的页面会出现在你已发布的站点上',
    },
    summary: {
      en: 'A page an agent adds under a page you published is now published with it, instead of quietly staying invisible to your visitors.',
      tr: 'Bir ajanın, yayınladığınız bir sayfanın altına eklediği sayfa artık onunla birlikte yayınlanıyor; eskiden sessizce ziyaretçilerinize görünmez kalıyordu.',
      de: 'Eine Seite, die ein Agent unter einer von Ihnen veröffentlichten Seite anlegt, wird jetzt mit veröffentlicht, statt für Ihre Besucher unsichtbar zu bleiben.',
      es: 'Una página que un agente añade bajo una página que publicaste ahora se publica con ella, en lugar de quedar invisible para tus visitantes.',
      fr: 'Une page qu’un agent ajoute sous une page que vous avez publiée est désormais publiée avec elle, au lieu de rester invisible pour vos visiteurs.',
      hi: 'आपकी प्रकाशित पेज के नीचे एजेंट जो पेज जोड़ता है, वह अब उसके साथ ही प्रकाशित होती है, न कि आपके विज़िटर्स से छिपी रह जाती है।',
      ru: 'Страница, которую агент добавляет под опубликованной вами страницей, теперь публикуется вместе с ней, а не остаётся невидимой для посетителей.',
      zh: '智能体在你已发布页面下新建的页面，现在会随之一起发布，不再悄悄地对访客隐藏。',
    },
  },
  {
    id: '2026-09-22-faster-workspace-setup',
    date: '2026-09-22',
    category: 'improved',
    title: {
      en: 'Setting up a workspace is far faster',
      tr: 'Çalışma alanı kurulumu çok daha hızlı',
      de: 'Ein Workspace ist viel schneller eingerichtet',
      es: 'Preparar un espacio de trabajo es mucho más rápido',
      fr: 'La mise en place d’un espace de travail est bien plus rapide',
      hi: 'वर्कस्पेस तैयार करना अब कहीं ज़्यादा तेज़',
      ru: 'Настройка рабочего пространства стала гораздо быстрее',
      zh: '搭建工作区快了很多',
    },
    summary: {
      en: 'When an agent fills your workspace with pages and rows, they now appear in seconds instead of minutes — and it can create up to 100 of them at a time.',
      tr: 'Bir ajan çalışma alanınızı sayfalar ve satırlarla doldururken bunlar artık dakikalar yerine saniyeler içinde beliriyor ve tek seferde 100 taneye kadar oluşturulabiliyor.',
      de: 'Wenn ein Agent Ihren Workspace mit Seiten und Zeilen füllt, erscheinen sie jetzt in Sekunden statt Minuten – und bis zu 100 Stück auf einmal.',
      es: 'Cuando un agente llena tu espacio de trabajo con páginas y filas, ahora aparecen en segundos en vez de minutos, y puede crear hasta 100 de una sola vez.',
      fr: 'Quand un agent remplit votre espace de travail de pages et de lignes, elles apparaissent désormais en quelques secondes au lieu de plusieurs minutes, et il peut en créer jusqu’à 100 d’un coup.',
      hi: 'कोई एजेंट जब आपके वर्कस्पेस में पेज और पंक्तियाँ भरता है, तो वे अब मिनटों के बजाय सेकंडों में दिखती हैं — और एक बार में 100 तक बन सकती हैं।',
      ru: 'Когда агент наполняет ваше пространство страницами и строками, они появляются за секунды, а не за минуты, и создаются до 100 штук за раз.',
      zh: '智能体往工作区里创建页面和条目时，现在几秒就能出现，而不是等上几分钟，一次最多可创建 100 条。',
    },
  },
  {
    id: '2026-09-22-join-a-project',
    date: '2026-09-22',
    category: 'new',
    title: {
      en: 'Bring your team into a project',
      tr: 'Ekibinizi projeye katın',
      de: 'Holen Sie Ihr Team ins Projekt',
      es: 'Suma a tu equipo al proyecto',
      fr: 'Faites entrer votre équipe dans un projet',
      hi: 'अपनी टीम को प्रोजेक्ट में जोड़ें',
      ru: 'Подключите команду к проекту',
      zh: '把团队拉进项目',
    },
    summary: {
      en: 'A teammate who opens a project you already connected can now get their own access with one command, and ask you for permission right there if they do not have it yet.',
      tr: 'Sizin bağladığınız bir projeyi açan ekip arkadaşınız artık tek komutla kendi erişimini alabiliyor, erişimi yoksa da oracıkta sizden izin isteyebiliyor.',
      de: 'Wer ein von Ihnen verbundenes Projekt öffnet, bekommt seinen eigenen Zugang jetzt mit einem einzigen Befehl – und kann Sie direkt dort um Freigabe bitten, falls er ihn noch nicht hat.',
      es: 'Quien abra un proyecto que ya conectaste puede obtener su propio acceso con un solo comando y, si aún no lo tiene, pedírtelo allí mismo.',
      fr: 'Un coéquipier qui ouvre un projet que vous avez déjà connecté obtient désormais son propre accès en une seule commande, et peut vous le demander sur place s’il ne l’a pas encore.',
      hi: 'आपके जोड़े हुए प्रोजेक्ट को खोलने वाला साथी अब एक ही कमांड से अपनी अलग पहुँच ले सकता है, और अगर पहुँच नहीं है तो वहीं से आपसे अनुमति माँग सकता है।',
      ru: 'Коллега, открывший подключённый вами проект, теперь получает собственный доступ одной командой, а если доступа ещё нет — тут же запрашивает его у вас.',
      zh: '打开你已连接项目的同事，现在一条命令就能拿到属于自己的访问权限；还没有权限时，也能就地向你申请。',
    },
  },
  {
    id: '2026-09-21-live-project-window',
    date: '2026-09-21',
    category: 'improved',
    title: {
      en: 'Watch your assistant work, live',
      tr: 'Asistanınızı canlı izleyin',
      de: 'Ihrem Assistenten live zusehen',
      es: 'Mira a tu asistente trabajar en vivo',
      fr: 'Suivez votre assistant en direct',
      hi: 'अपने असिस्टेंट को लाइव काम करते देखें',
      ru: 'Смотрите, как ассистент работает',
      zh: '实时查看助手的工作',
    },
    summary: {
      en: 'Pages your assistant creates, renames or deletes now appear in the sidebar within a couple of seconds instead of after a wait, and a project window shows only the things that work inside that project.',
      tr: 'Asistanınızın oluşturduğu, yeniden adlandırdığı veya sildiği sayfalar artık kenar çubuğunda birkaç saniye içinde görünüyor ve proje penceresi yalnızca o projede işe yarayan şeyleri gösteriyor.',
      de: 'Seiten, die Ihr Assistent anlegt, umbenennt oder löscht, erscheinen jetzt innerhalb weniger Sekunden in der Seitenleiste, und ein Projektfenster zeigt nur noch das, was in diesem Projekt funktioniert.',
      es: 'Las páginas que tu asistente crea, renombra o elimina aparecen ahora en la barra lateral en un par de segundos, y una ventana de proyecto muestra solo lo que funciona dentro de ese proyecto.',
      fr: 'Les pages que votre assistant crée, renomme ou supprime apparaissent désormais dans la barre latérale en quelques secondes, et une fenêtre de projet n’affiche plus que ce qui fonctionne dans ce projet.',
      hi: 'आपका असिस्टेंट जो पेज बनाता, नाम बदलता या हटाता है वे अब कुछ ही सेकंड में साइडबार में दिखते हैं, और प्रोजेक्ट विंडो सिर्फ वही दिखाती है जो उस प्रोजेक्ट में काम करता है।',
      ru: 'Страницы, которые ассистент создаёт, переименовывает или удаляет, теперь появляются в боковой панели за пару секунд, а окно проекта показывает только то, что работает внутри этого проекта.',
      zh: '助手新建、重命名或删除的页面现在几秒内就会出现在侧边栏，项目窗口也只保留在该项目中真正可用的内容。',
    },
  },
  {
    id: '2026-09-15-organized-agent-workspaces',
    date: '2026-09-15',
    category: 'improved',
    title: {
      en: 'Agent-built workspaces come organized',
      tr: 'Yapay zekânın kurduğu çalışma alanları düzenli gelir',
      de: 'Von KI-Assistenten eingerichtete Arbeitsbereiche sind geordnet',
      es: 'Los espacios creados por asistentes de IA llegan organizados',
      fr: 'Les espaces créés par un assistant IA arrivent organisés',
      hi: 'AI असिस्टेंट के बनाए workspace व्यवस्थित आते हैं',
      ru: 'Пространства, созданные ИИ-ассистентом, сразу упорядочены',
      zh: 'AI 助手搭建的工作区更有条理',
    },
    summary: {
      en: 'When an AI assistant sets up your workspace, pages now arrive nested under clear sections with icons, databases come with ready-made board and calendar views, and the whole setup finishes much faster.',
      tr: 'Bir yapay zekâ asistanı çalışma alanınızı kurduğunda sayfalar artık ikonlarıyla net bölümlerin altında düzenli geliyor, veritabanları hazır pano ve takvim görünümleriyle açılıyor ve kurulum çok daha hızlı bitiyor.',
      de: 'Wenn ein KI-Assistent Ihren Arbeitsbereich einrichtet, erscheinen Seiten jetzt mit Symbolen unter klaren Abschnitten, Datenbanken bringen fertige Board- und Kalenderansichten mit, und die Einrichtung ist deutlich schneller fertig.',
      es: 'Cuando un asistente de IA configura tu espacio de trabajo, las páginas llegan ahora ordenadas en secciones claras y con iconos, las bases de datos traen vistas de tablero y calendario listas y todo termina mucho más rápido.',
      fr: 'Quand un assistant IA configure votre espace de travail, les pages arrivent désormais rangées dans des sections claires avec des icônes, les bases de données ont déjà leurs vues tableau et calendrier, et le tout se termine bien plus vite.',
      hi: 'जब कोई AI असिस्टेंट आपका workspace सेट करता है, तो पेज अब आइकन के साथ साफ़ सेक्शन के अंदर व्यवस्थित आते हैं, डेटाबेस में बोर्ड और कैलेंडर व्यू पहले से तैयार होते हैं, और पूरा सेटअप कहीं ज़्यादा तेज़ी से पूरा होता है।',
      ru: 'Когда ИИ-ассистент настраивает ваше пространство, страницы теперь сразу разложены по понятным разделам и снабжены значками, у баз данных уже есть доски и календари, а вся настройка проходит гораздо быстрее.',
      zh: '当 AI 助手为你搭建工作区时，页面现在会带着图标归入清晰的分区，数据库自带看板和日历视图，整个搭建过程也快得多。',
    },
  },
  {
    id: '2026-09-15-project-window-signed-in',
    date: '2026-09-15',
    category: 'improved',
    title: {
      en: 'Project windows open signed in',
      tr: 'Proje penceresi giriş yapmış olarak açılır',
      de: 'Projektfenster öffnen sich angemeldet',
      es: 'Las ventanas de proyecto se abren con la sesión iniciada',
      fr: 'Les fenêtres de projet s’ouvrent déjà connectées',
      hi: 'प्रोजेक्ट विंडो साइन-इन के साथ खुलती है',
      ru: 'Окно проекта открывается уже с выполненным входом',
      zh: '项目窗口打开时已登录',
    },
    summary: {
      en: 'Opening a project’s workspace from your coding agent no longer asks you to sign in, and that window shows only that project’s workspace.',
      tr: 'Kodlama asistanınızdan bir projenin çalışma alanını açtığınızda artık giriş yapmanız istenmiyor ve bu pencere yalnızca o projenin çalışma alanını gösteriyor.',
      de: 'Wenn Sie den Arbeitsbereich eines Projekts aus Ihrem Coding-Agenten öffnen, müssen Sie sich nicht mehr anmelden, und dieses Fenster zeigt nur den Arbeitsbereich dieses Projekts.',
      es: 'Al abrir el espacio de trabajo de un proyecto desde tu agente de programación ya no se te pide iniciar sesión, y esa ventana muestra solo el espacio de trabajo de ese proyecto.',
      fr: 'Ouvrir l’espace de travail d’un projet depuis votre agent de code ne vous demande plus de vous connecter, et cette fenêtre n’affiche que l’espace de travail de ce projet.',
      hi: 'अपने कोडिंग एजेंट से किसी प्रोजेक्ट का workspace खोलने पर अब साइन इन नहीं करना पड़ता, और वह विंडो सिर्फ़ उसी प्रोजेक्ट का workspace दिखाती है।',
      ru: 'Когда вы открываете пространство проекта из своего ИИ-агента, входить больше не нужно, а это окно показывает только пространство этого проекта.',
      zh: '从编码助手打开项目的工作区时不再需要登录，而且该窗口只显示这个项目的工作区。',
    },
  },
  {
    id: '2026-09-14-workspace-opens-on-session-start',
    date: '2026-09-14',
    category: 'new',
    title: {
      en: 'Your workspace opens itself when you start coding',
      tr: 'Kodlamaya başladığınızda çalışma alanınız kendiliğinden açılıyor',
      de: 'Ihr Arbeitsbereich öffnet sich, wenn Sie mit dem Programmieren beginnen',
      es: 'Tu espacio de trabajo se abre solo cuando empiezas a programar',
      fr: 'Votre espace de travail s\'ouvre dès que vous commencez à coder',
      hi: 'कोडिंग शुरू करते ही आपका वर्कस्पेस खुद खुल जाता है',
      ru: 'Ваше пространство открывается само, когда вы начинаете кодить',
      zh: '开始写代码时，您的工作区会自动打开',
    },
    summary: {
      en: 'In a project connected to Remnus, starting a fresh Claude Code session now opens that project\'s workspace in your browser on its own — or run `npx remnus open` any time.',
      tr: 'Remnus\'a bağlı bir projede yeni bir Claude Code oturumu başlattığınızda, o projenin çalışma alanı artık tarayıcınızda kendiliğinden açılıyor — istediğiniz an `npx remnus open` da çalıştırabilirsiniz.',
      de: 'In einem mit Remnus verbundenen Projekt öffnet eine neue Claude-Code-Sitzung den Arbeitsbereich jetzt von selbst im Browser — oder führen Sie jederzeit `npx remnus open` aus.',
      es: 'En un proyecto conectado a Remnus, iniciar una nueva sesión de Claude Code ahora abre el espacio de trabajo de ese proyecto en tu navegador por su cuenta, o ejecuta `npx remnus open` en cualquier momento.',
      fr: 'Dans un projet connecté à Remnus, démarrer une nouvelle session Claude Code ouvre désormais automatiquement l\'espace de travail du projet dans votre navigateur — ou lancez `npx remnus open` à tout moment.',
      hi: 'Remnus से जुड़े प्रोजेक्ट में, नया Claude Code सेशन शुरू करने पर अब वह प्रोजेक्ट वर्कस्पेस आपके ब्राउज़र में स्वयं खुल जाता है — या कभी भी `npx remnus open` चलाएँ।',
      ru: 'В проекте, подключённом к Remnus, запуск новой сессии Claude Code теперь сам открывает пространство этого проекта в браузере — или запустите `npx remnus open` в любой момент.',
      zh: '在已连接 Remnus 的项目中，启动新的 Claude Code 会话现在会自动在浏览器中打开该项目的工作区——也可以随时运行 `npx remnus open`。',
    },
  },
  {
    id: '2026-09-13-workspace-auto-setup',
    date: '2026-09-13',
    category: 'improved',
    title: {
      en: 'Your AI assistant sets up the new workspace for you',
      tr: 'Yapay zekâ asistanınız yeni çalışma alanını sizin için kuruyor',
      de: 'Ihr KI-Assistent richtet den neuen Arbeitsbereich für Sie ein',
      es: 'Tu asistente de IA configura el nuevo espacio de trabajo por ti',
      fr: 'Votre assistant IA configure le nouvel espace de travail pour vous',
      hi: 'आपका AI असिस्टेंट नया वर्कस्पेस आपके लिए सेट करता है',
      ru: 'Ваш ИИ-ассистент сам настраивает новое пространство',
      zh: '您的 AI 助手会自动为您搭建新工作区',
    },
    summary: {
      en: 'After connecting a project, your AI assistant now reads it and fills the new workspace with pages that match it instead of handing you an empty one.',
      tr: 'Bir proje bağlandıktan sonra, yapay zekâ asistanınız artık projeyi okuyup yeni çalışma alanını ona uygun sayfalarla dolduruyor; size boş bir alan bırakmıyor.',
      de: 'Nach dem Verbinden eines Projekts liest Ihr KI-Assistent es jetzt und füllt den neuen Arbeitsbereich mit passenden Seiten, statt ihn leer zu lassen.',
      es: 'Tras conectar un proyecto, tu asistente de IA ahora lo lee y llena el nuevo espacio de trabajo con páginas que encajan, en vez de dejarlo vacío.',
      fr: 'Après avoir connecté un projet, votre assistant IA le lit désormais et remplit le nouvel espace de travail avec des pages adaptées, au lieu de vous le laisser vide.',
      hi: 'प्रोजेक्ट जोड़ने के बाद अब आपका AI असिस्टेंट उसे पढ़कर नए वर्कस्पेस को उपयुक्त पेजों से भर देता है, इसे खाली नहीं छोड़ता।',
      ru: 'После подключения проекта ваш ИИ-ассистент теперь читает его и сразу наполняет новое пространство подходящими страницами, а не оставляет его пустым.',
      zh: '连接项目后，您的 AI 助手现在会读取项目内容并用匹配的页面填充新工作区，而不是留一个空的给您。',
    },
  },
  {
    id: '2026-09-13-login-return-link',
    date: '2026-09-13',
    category: 'fixed',
    title: {
      en: 'Sign-in returns you to the right page',
      tr: 'Giriş yaptıktan sonra doğru sayfaya dönüyorsunuz',
      de: 'Anmeldung führt zur richtigen Seite zurück',
      es: 'El inicio de sesión te lleva a la página correcta',
      fr: 'La connexion vous ramène à la bonne page',
      hi: 'साइन इन करने पर अब सही पेज पर वापस जाते हैं',
      ru: 'Вход возвращает вас на нужную страницу',
      zh: '登录后会直接回到正确的页面',
    },
    summary: {
      en: 'Signing in after following a shared link or setup step now takes you straight back to it instead of dropping you on your general workspace.',
      tr: 'Paylaşılan bir bağlantıdan veya kurulum adımından gelip giriş yaptığınızda artık genel çalışma alanına değil, doğrudan geldiğiniz yere dönüyorsunuz.',
      de: 'Wenn Sie sich über einen geteilten Link oder einen Einrichtungsschritt anmelden, gelangen Sie jetzt direkt dorthin zurück statt in den allgemeinen Arbeitsbereich.',
      es: 'Al iniciar sesión tras seguir un enlace compartido o un paso de configuración, ahora vuelves directamente allí en vez de a tu espacio de trabajo general.',
      fr: 'En vous connectant après avoir suivi un lien partagé ou une étape de configuration, vous êtes maintenant ramené directement à cet endroit plutôt qu\'à votre espace de travail général.',
      hi: 'किसी शेयर की गई लिंक या सेटअप स्टेप से आकर साइन इन करने पर अब आप सामान्य वर्कस्पेस के बजाय सीधे वहीं वापस पहुँचते हैं।',
      ru: 'После входа по общей ссылке или на шаге настройки вы теперь попадаете именно туда, а не в общее рабочее пространство.',
      zh: '通过分享链接或设置步骤登录后，现在会直接回到原来的位置，而不是跳转到通用工作区。',
    },
  },
  {
    id: '2026-09-08-project-setup-command',
    date: '2026-09-08',
    category: 'new',
    title: {
      en: 'Connect a project in one command',
      tr: 'Projeyi tek komutla bağlayın',
      de: 'Projekt mit einem Befehl verbinden',
      es: 'Conecta un proyecto con un solo comando',
      fr: 'Connectez un projet en une commande',
      hi: 'एक कमांड में प्रोजेक्ट जोड़ें',
      ru: 'Подключение проекта одной командой',
      zh: '一条命令连接项目',
    },
    summary: {
      en: 'Run one command in a project folder and sign in once, and that project gets its own Remnus workspace your AI assistant can read and keep up to date.',
      tr: 'Proje klasöründe tek bir komut çalıştırıp bir kez giriş yapın; o proje, yapay zekâ asistanınızın okuyup güncel tutabileceği kendi Remnus çalışma alanına kavuşsun.',
      de: 'Führen Sie einen Befehl im Projektordner aus und melden Sie sich einmal an — das Projekt bekommt seinen eigenen Remnus-Arbeitsbereich, den Ihr KI-Assistent lesen und aktuell halten kann.',
      es: 'Ejecuta un comando en la carpeta del proyecto e inicia sesión una vez, y ese proyecto tendrá su propio espacio de trabajo de Remnus que tu asistente de IA puede leer y mantener al día.',
      fr: 'Lancez une commande dans le dossier du projet et connectez-vous une seule fois : ce projet obtient son propre espace de travail Remnus que votre assistant IA peut lire et tenir à jour.',
      hi: 'प्रोजेक्ट फ़ोल्डर में एक कमांड चलाएँ और एक बार साइन इन करें, और उस प्रोजेक्ट को अपना Remnus workspace मिल जाता है जिसे आपका AI असिस्टेंट पढ़ और अपडेट रख सकता है।',
      ru: 'Запустите одну команду в папке проекта и войдите один раз — проект получит собственное пространство Remnus, которое ваш ИИ-ассистент сможет читать и поддерживать в актуальном состоянии.',
      zh: '在项目文件夹里运行一条命令并登录一次，这个项目就有了自己的 Remnus 工作区，你的 AI 助手可以读取并保持它是最新的。',
    },
  },
  {
    id: '2026-09-01-page-history',
    date: '2026-09-01',
    category: 'new',
    title: {
      en: 'Version history for every page',
      tr: 'Her sayfa için sürüm geçmişi',
      de: 'Versionsverlauf für jede Seite',
      es: 'Historial de versiones para cada página',
      fr: 'Historique des versions pour chaque page',
      hi: 'हर पेज के लिए वर्जन हिस्ट्री',
      ru: 'История версий для каждой страницы',
      zh: '每个页面的版本历史',
    },
    summary: {
      en: 'Every page and row now keeps a short history of earlier versions — open it from the "..." menu to preview or bring back an older one, including edits your AI agents made.',
      tr: 'Artık her sayfa ve satır, önceki sürümlerinin kısa bir geçmişini tutuyor — "..." menüsünden açıp AI ajanlarınızın yaptığı değişiklikler dahil eski bir sürümü önizleyebilir veya geri getirebilirsiniz.',
      de: 'Jede Seite und Zeile behält jetzt einen kurzen Verlauf früherer Versionen — öffnen Sie ihn über das „…"-Menü, um eine ältere Version anzusehen oder wiederherzustellen, einschließlich Änderungen Ihrer KI-Agenten.',
      es: 'Cada página y fila ahora conserva un breve historial de versiones anteriores — ábrelo desde el menú "..." para previsualizar o restaurar una versión anterior, incluidos los cambios hechos por tus agentes de IA.',
      fr: 'Chaque page et ligne conserve désormais un bref historique de ses versions précédentes — ouvrez-le depuis le menu « ... » pour prévisualiser ou restaurer une version antérieure, y compris les modifications faites par vos agents IA.',
      hi: 'अब हर पेज और रो पिछले वर्ज़न्स का एक संक्षिप्त इतिहास रखता है — "..." मेनू से खोलकर किसी पुराने वर्ज़न को देख सकते हैं या वापस ला सकते हैं, आपके AI एजेंट्स द्वारा किए बदलाव भी शामिल।',
      ru: 'Теперь каждая страница и строка хранит краткую историю прежних версий — откройте её из меню «...», чтобы просмотреть или восстановить более раннюю версию, включая изменения ваших ИИ-агентов.',
      zh: '现在每个页面和行都会保留一份简短的历史版本记录——从"..."菜单打开即可预览或恢复较早的版本，包括你的 AI 代理所做的更改。',
    },
  },
  {
    id: '2026-09-01-bulk-delete-move',
    date: '2026-09-01',
    category: 'new',
    title: {
      en: 'Bulk delete and move for AI agents',
      tr: 'AI ajanları için toplu silme ve taşıma',
      de: 'Massenlöschen und -verschieben für KI-Agenten',
      es: 'Eliminación y movimiento masivo para agentes de IA',
      fr: 'Suppression et déplacement en masse pour les agents IA',
      hi: 'AI एजेंट्स के लिए बल्क डिलीट और मूव',
      ru: 'Массовое удаление и перемещение для ИИ-агентов',
      zh: 'AI 代理的批量删除与移动',
    },
    summary: {
      en: 'Your connected AI agents can now delete or move many pages, rows, or boards at once, and always know exactly which ones succeeded.',
      tr: 'Bağlı AI ajanlarınız artık birden fazla sayfayı, satırı veya panoyu tek seferde silebilir ya da taşıyabilir ve hangilerinin başarılı olduğunu her zaman tam olarak bilir.',
      de: 'Ihre verbundenen KI-Agenten können jetzt viele Seiten, Zeilen oder Boards auf einmal löschen oder verschieben und wissen dabei immer genau, welche davon erfolgreich waren.',
      es: 'Tus agentes de IA conectados ahora pueden eliminar o mover muchas páginas, filas o tableros a la vez, y siempre saben exactamente cuáles se completaron correctamente.',
      fr: 'Vos agents IA connectés peuvent désormais supprimer ou déplacer de nombreuses pages, lignes ou tableaux en une seule fois, en sachant toujours exactement lesquels ont réussi.',
      hi: 'आपके कनेक्टेड AI एजेंट अब कई पेज, रो या बोर्ड एक साथ डिलीट या मूव कर सकते हैं, और हमेशा ठीक-ठीक जानते हैं कि कौन-से सफल हुए।',
      ru: 'Ваши подключённые ИИ-агенты теперь могут удалять или перемещать сразу много страниц, строк или досок, и всегда точно знают, какие из них выполнились успешно.',
      zh: '你连接的 AI 代理现在可以一次删除或移动多个页面、行或看板，并且始终清楚知道哪些操作成功了。',
    },
  },
  {
    id: '2026-09-01-trash-restore',
    date: '2026-09-01',
    category: 'new',
    title: {
      en: 'A trash for anything that gets deleted',
      tr: 'Silinen her şey için çöp kutusu',
      de: 'Ein Papierkorb für alles, was gelöscht wird',
      es: 'Una papelera para todo lo que se elimina',
      fr: 'Une corbeille pour tout ce qui est supprimé',
      hi: 'जो भी डिलीट होता है उसके लिए एक ट्रैश',
      ru: 'Корзина для всего удалённого',
      zh: '为所有被删除内容提供回收站',
    },
    summary: {
      en: 'Deleted pages, rows and boards now sit in a Trash inside Workspace Settings for 30 days, ready to restore with one click if something was removed by mistake.',
      tr: 'Silinen sayfalar, satırlar ve panolar artık 30 gün boyunca Workspace Ayarları içindeki Çöp Kutusu\'nda bekler; yanlışlıkla bir şey silindiyse tek tıkla geri yükleyebilirsiniz.',
      de: 'Gelöschte Seiten, Zeilen und Boards liegen jetzt 30 Tage lang im Papierkorb in den Workspace-Einstellungen und lassen sich mit einem Klick wiederherstellen, falls etwas versehentlich entfernt wurde.',
      es: 'Las páginas, filas y tableros eliminados ahora permanecen 30 días en la Papelera dentro de la Configuración del espacio de trabajo, listos para restaurarse con un clic si algo se eliminó por error.',
      fr: 'Les pages, lignes et tableaux supprimés restent désormais 30 jours dans la Corbeille des paramètres de l\'espace de travail, prêts à être restaurés en un clic en cas de suppression accidentelle.',
      hi: 'डिलीट किए गए पेज, रो और बोर्ड अब वर्कस्पेस सेटिंग्स के अंदर ट्रैश में 30 दिनों तक रहते हैं, और गलती से कुछ हट जाने पर एक क्लिक में पुनर्स्थापित किए जा सकते हैं।',
      ru: 'Удалённые страницы, строки и доски теперь 30 дней хранятся в Корзине в настройках рабочего пространства и восстанавливаются одним щелчком, если что-то удалено по ошибке.',
      zh: '已删除的页面、行和看板现在会在工作区设置的回收站中保留 30 天，如果误删了什么内容，可以一键恢复。',
    },
  },
  {
    id: '2026-08-31-card-comments',
    date: '2026-08-31',
    category: 'new',
    title: {
      en: 'Comments on every card',
      tr: 'Her kartta yorumlar',
      de: 'Kommentare auf jeder Karte',
      es: 'Comentarios en cada tarjeta',
      fr: 'Commentaires sur chaque carte',
      hi: 'हर कार्ड पर टिप्पणियाँ',
      ru: 'Комментарии на каждой карточке',
      zh: '每张卡片都可以评论',
    },
    summary: {
      en: 'You can now leave running comments on any page or card, including notes your AI agents add as they work, in a thread that stays separate from the content itself.',
      tr: 'Artık her sayfaya veya karta, ajanlarınızın çalışırken bıraktığı notlar da dahil, içerikten ayrı bir akışta yorum bırakabilirsiniz.',
      de: 'Sie können jetzt auf jeder Seite oder Karte fortlaufend Kommentare hinterlassen, einschließlich Notizen, die Ihre KI-Agenten während der Arbeit hinzufügen, in einem Thread, der vom eigentlichen Inhalt getrennt bleibt.',
      es: 'Ahora puedes dejar comentarios continuos en cualquier página o tarjeta, incluidas las notas que tus agentes de IA añaden mientras trabajan, en un hilo que se mantiene separado del contenido.',
      fr: 'Vous pouvez désormais laisser des commentaires continus sur n’importe quelle page ou carte, y compris les notes que vos agents IA ajoutent pendant leur travail, dans un fil séparé du contenu lui-même.',
      hi: 'अब आप किसी भी पेज या कार्ड पर लगातार टिप्पणियाँ छोड़ सकते हैं, जिसमें आपके AI एजेंट काम करते समय जोड़े गए नोट्स भी शामिल हैं, एक ऐसे थ्रेड में जो सामग्री से अलग रहता है।',
      ru: 'Теперь вы можете оставлять комментарии на любой странице или карточке, включая заметки, которые ваши ИИ-агенты добавляют по ходу работы, в отдельной от самого содержимого ветке.',
      zh: '现在你可以在任何页面或卡片上持续添加评论，包括你的 AI 代理在工作过程中留下的备注，评论会保留在一个与内容本身分开的独立讨论区中。',
    },
  },
  {
    id: '2026-08-24-code-block-paste-stays-inside',
    date: '2026-08-24',
    category: 'fixed',
    title: {
      en: 'Pasting into a code block stays in the block',
      tr: 'Kod bloğuna yapıştırma artık bloğun içinde kalıyor',
      de: 'Einfügen in einen Codeblock bleibt im Block',
      es: 'Pegar en un bloque de código se queda dentro',
      fr: 'Le collage dans un bloc de code y reste',
      hi: 'कोड ब्लॉक में चिपकाया गया टेक्स्ट ब्लॉक के अंदर ही रहता है',
      ru: 'Вставка в блок кода остаётся в блоке',
      zh: '粘贴到代码块的内容不再跳出',
    },
    summary: {
      en: 'Text that looks like markdown — headings, lists, quotes or another set of backticks — now stays inside the code block you paste it into, exactly as written, instead of escaping the block and turning into real headings and lists underneath it.',
      tr: 'Başlık, liste, alıntı veya bir başka üç tırnak içeren markdown görünümlü metinler artık yapıştırdığınız kod bloğunun dışına taşıp altta gerçek başlıklara ve listelere dönüşmüyor, yazdığınız gibi bloğun içinde kalıyor.',
      de: 'Text, der wie Markdown aussieht – Überschriften, Listen, Zitate oder weitere Backticks –, bleibt jetzt genau so, wie er geschrieben ist, in dem Codeblock, in den Sie ihn einfügen, statt aus dem Block auszubrechen und darunter zu echten Überschriften und Listen zu werden.',
      es: 'El texto que parece Markdown —títulos, listas, citas u otro juego de comillas invertidas— ahora se queda tal cual dentro del bloque de código en el que lo pegas, en lugar de salirse del bloque y convertirse en títulos y listas reales debajo.',
      fr: 'Le texte qui ressemble à du Markdown — titres, listes, citations ou une autre série de backticks — reste désormais tel quel dans le bloc de code où vous le collez, au lieu d’en sortir et de se transformer en véritables titres et listes en dessous.',
      hi: 'मार्कडाउन जैसा दिखने वाला टेक्स्ट — शीर्षक, सूचियाँ, उद्धरण या बैकटिक का एक और सेट — अब जिस कोड ब्लॉक में आप उसे चिपकाते हैं उसी के अंदर ज्यों का त्यों रहता है, ब्लॉक से बाहर निकलकर नीचे असली शीर्षकों और सूचियों में नहीं बदलता।',
      ru: 'Текст, похожий на Markdown, — заголовки, списки, цитаты или ещё одна пара обратных кавычек — теперь остаётся в блоке кода, куда вы его вставили, ровно в том виде, в каком написан, а не вырывается наружу и не превращается в настоящие заголовки и списки под ним.',
      zh: '看起来像 Markdown 的文本——标题、列表、引用或又一组反引号——现在会原样留在你粘贴进去的代码块内，而不再跳出代码块、在下方变成真正的标题和列表。',
    },
  },
  {
    id: '2026-08-21-claude-desktop-connect-fix',
    date: '2026-08-21',
    category: 'fixed',
    title: {
      en: 'Claude Desktop connects on the first try',
      tr: 'Claude Desktop ilk denemede bağlanıyor',
      de: 'Claude Desktop verbindet sich beim ersten Versuch',
      es: 'Claude Desktop se conecta al primer intento',
      fr: 'Claude Desktop se connecte du premier coup',
      hi: 'Claude Desktop पहली ही बार में कनेक्ट हो जाता है',
      ru: 'Claude Desktop подключается с первого раза',
      zh: 'Claude Desktop 首次尝试即可连接',
    },
    summary: {
      en: 'Adding Remnus to Claude Desktop no longer leaves you stuck on an "unable to connect" message after you sign in — the connection now finishes the first time, even when Claude starts several sessions at once.',
      tr: 'Remnus’u Claude Desktop’a eklerken oturum açtıktan sonra artık “bağlanılamıyor” uyarısında takılı kalmıyorsunuz; Claude aynı anda birden fazla oturum başlatsa bile bağlantı ilk seferde tamamlanıyor.',
      de: 'Beim Hinzufügen von Remnus zu Claude Desktop bleiben Sie nach der Anmeldung nicht mehr bei „Verbindung nicht möglich“ hängen – die Verbindung kommt jetzt beim ersten Mal zustande, selbst wenn Claude mehrere Sitzungen gleichzeitig startet.',
      es: 'Al añadir Remnus a Claude Desktop ya no te quedas atascado en el mensaje «no se puede conectar» después de iniciar sesión: la conexión ahora se completa a la primera, incluso cuando Claude abre varias sesiones a la vez.',
      fr: 'L’ajout de Remnus à Claude Desktop ne vous laisse plus bloqué sur un message « connexion impossible » après votre connexion : la liaison aboutit désormais du premier coup, même lorsque Claude démarre plusieurs sessions en même temps.',
      hi: 'Claude Desktop में Remnus जोड़ते समय साइन इन करने के बाद अब आप “कनेक्ट नहीं हो सका” संदेश पर अटके नहीं रहते — अब कनेक्शन पहली ही बार पूरा हो जाता है, भले ही Claude एक साथ कई सत्र शुरू करे।',
      ru: 'При добавлении Remnus в Claude Desktop вы больше не застреваете на сообщении «не удалось подключиться» после входа — соединение теперь устанавливается с первого раза, даже если Claude запускает сразу несколько сеансов.',
      zh: '将 Remnus 添加到 Claude Desktop 时，登录后不会再卡在“无法连接”的提示上——即使 Claude 同时启动多个会话，连接现在也能一次成功。',
    },
  },
  {
    id: '2026-08-21-recurring-series-confirmations',
    date: '2026-08-21',
    category: 'fixed',
    title: {
      en: 'Recurring card actions ask first, then confirm',
      tr: 'Tekrarlayan kart işlemleri artık önce soruyor, sonra doğruluyor',
      de: 'Aktionen an wiederkehrenden Karten fragen jetzt erst nach',
      es: 'Las acciones en tarjetas periódicas ahora preguntan primero',
      fr: 'Les actions sur les cartes récurrentes demandent désormais confirmation',
      hi: 'दोहराने वाले कार्ड पर कार्रवाई अब पहले पूछती है, फिर पुष्टि करती है',
      ru: 'Действия с повторяющимися карточками теперь сначала спрашивают',
      zh: '重复卡片的操作现在会先询问，再确认',
    },
    summary: {
      en: 'Removing the repeat pattern from a series now asks whether that should apply from this card on or to the whole series (it used to unlink every card instantly with no way to scope it down), and both that action and deleting a repeating card now confirm what happened afterward — how many cards were kept or unlinked, or a clear error — instead of going silent.',
      tr: 'Bir seriden tekrarlamayı kaldırmak artık bunun bu karttan itibaren mi yoksa serinin tamamı için mi geçerli olacağını soruyor (öncesinde tek tıkla, kapsam seçmeden anında tüm kartların bağlantısını koparıyordu); hem bu işlem hem de tekrarlayan bir kartı silmek artık ne olduğunu — kaç kartın korunduğunu/seriden çıkarıldığını ya da net bir hatayı — sonradan doğruluyor, sessiz kalmıyor.',
      de: 'Das Entfernen der Wiederholung aus einer Serie fragt jetzt, ob das ab dieser Karte oder für die gesamte Serie gelten soll (bisher wurden sofort alle Karten ohne Auswahlmöglichkeit entkoppelt); sowohl diese Aktion als auch das Löschen einer wiederkehrenden Karte bestätigen jetzt im Anschluss, was passiert ist – wie viele Karten beibehalten oder entkoppelt wurden, oder einen klaren Fehler – statt stumm zu bleiben.',
      es: 'Quitar la repetición de una serie ahora pregunta si debe aplicarse desde esta tarjeta en adelante o a toda la serie (antes desvinculaba todas las tarjetas al instante sin poder elegir el alcance); tanto esa acción como eliminar una tarjeta periódica ahora confirman después qué pasó —cuántas tarjetas se mantuvieron o desvincularon, o un error claro— en lugar de quedarse en silencio.',
      fr: 'Retirer la répétition d’une série demande désormais si cela doit s’appliquer à partir de cette carte ou à toute la série (auparavant, toutes les cartes étaient dissociées instantanément sans possibilité de choisir la portée) ; cette action comme la suppression d’une carte récurrente confirment maintenant ce qui s’est passé — combien de cartes ont été conservées ou dissociées, ou une erreur claire — au lieu de rester silencieuses.',
      hi: 'किसी शृंखला से दोहराव हटाना अब पूछता है कि यह इस कार्ड से आगे के लिए हो या पूरी शृंखला के लिए (पहले यह बिना कोई दायरा चुने तुरंत सभी कार्डों को अलग कर देता था); यह कार्रवाई और दोहराने वाला कार्ड हटाना, दोनों अब बाद में पुष्टि करते हैं कि क्या हुआ — कितने कार्ड रखे गए या अलग किए गए, या एक स्पष्ट त्रुटि — चुप रहने के बजाय।',
      ru: 'Удаление повтора из серии теперь спрашивает, применить ли это начиная с этой карточки или ко всей серии (раньше все карточки мгновенно отвязывались без возможности выбрать область действия); и это действие, и удаление повторяющейся карточки теперь показывают, что произошло — сколько карточек сохранено или отвязано, либо явную ошибку — вместо тишины.',
      zh: '从系列中移除重复现在会询问是从这张卡片开始生效，还是应用于整个系列（以前会立即取消所有卡片的关联，且无法选择范围）；这个操作和删除重复卡片现在都会在之后确认发生了什么——保留或取消关联了多少张卡片，或明确的错误提示——而不再是毫无反应。',
    },
  },
  {
    id: '2026-08-20-calendar-today-marker',
    date: '2026-08-20',
    category: 'improved',
    title: {
      en: 'Today stands out in the calendar',
      tr: 'Takvimde bugün belirgin',
      de: 'Heute fällt im Kalender auf',
      es: 'Hoy destaca en el calendario',
      fr: 'Aujourd’hui ressort dans le calendrier',
      hi: 'कैलेंडर में आज अलग दिखता है',
      ru: 'Сегодняшний день заметен в календаре',
      zh: '日历中今天更醒目',
    },
    summary: {
      en: 'The current day in Calendar view is now highlighted more strongly and labelled “Today” right next to its date, so you can find it without counting squares.',
      tr: 'Takvim görünümünde bugünün karesi artık daha belirgin vurgulanıyor ve tarihinin hemen yanında “Bugün” yazıyor; kareleri saymadan bulabiliyorsun.',
      de: 'Der heutige Tag in der Kalenderansicht ist jetzt deutlicher hervorgehoben und direkt neben dem Datum mit „Heute“ beschriftet, sodass du ihn ohne Suchen findest.',
      es: 'El día actual en la vista de Calendario ahora se resalta con más fuerza y lleva la etiqueta «Hoy» junto a su fecha, así lo encuentras sin contar casillas.',
      fr: 'Le jour en cours dans la vue Calendrier est désormais mis en évidence plus nettement et porte la mention « Aujourd’hui » juste à côté de sa date, pour le repérer d’un coup d’œil.',
      hi: 'कैलेंडर व्यू में आज का दिन अब ज़्यादा स्पष्ट रूप से हाइलाइट होता है और उसकी तारीख़ के ठीक बगल में “आज” लिखा रहता है, जिससे वह तुरंत मिल जाता है।',
      ru: 'Текущий день в Календаре теперь выделен заметнее и подписан «Сегодня» рядом с датой — его легко найти с первого взгляда.',
      zh: '日历视图中的当天现在高亮更明显，并在日期旁标注“今天”，一眼就能找到。',
    },
  },
  {
    id: '2026-08-20-collapsible-table-groups',
    date: '2026-08-20',
    category: 'new',
    title: {
      en: 'Collapse groups in a grouped table',
      tr: 'Gruplu tabloda grupları katla',
      de: 'Gruppen in der gruppierten Tabelle einklappen',
      es: 'Contrae grupos en la tabla agrupada',
      fr: 'Réduis les groupes dans le tableau groupé',
      hi: 'समूहित तालिका में समूह छोटे करें',
      ru: 'Сворачивайте группы в сгруппированной таблице',
      zh: '折叠分组表格中的分组',
    },
    summary: {
      en: 'In a grouped table you can now fold any group down to its header, so only the rows you are working on stay on screen.',
      tr: 'Gruplu tablo görünümünde artık istediğin grubu başlığına kadar katlayabiliyorsun; böylece ekranda yalnızca üzerinde çalıştığın satırlar kalıyor.',
      de: 'In einer gruppierten Tabelle kannst du jede Gruppe jetzt auf ihre Überschrift zusammenklappen, sodass nur die Zeilen sichtbar bleiben, an denen du gerade arbeitest.',
      es: 'En una tabla agrupada ahora puedes plegar cualquier grupo hasta su encabezado, de modo que en pantalla solo queden las filas con las que estás trabajando.',
      fr: 'Dans un tableau groupé, tu peux désormais replier n’importe quel groupe sur son en-tête pour ne garder à l’écran que les lignes sur lesquelles tu travailles.',
      hi: 'अब समूहित तालिका में आप किसी भी समूह को उसके शीर्षक तक समेट सकते हैं, ताकि स्क्रीन पर सिर्फ़ वही पंक्तियाँ रहें जिन पर आप काम कर रहे हैं।',
      ru: 'В сгруппированной таблице теперь можно свернуть любую группу до заголовка, чтобы на экране остались только нужные вам строки.',
      zh: '在分组表格中，你现在可以把任意分组收起到只剩标题，屏幕上只留下你正在处理的行。',
    },
  },
  {
    id: '2026-08-20-collapse-all-cards',
    date: '2026-08-20',
    category: 'improved',
    title: {
      en: 'Collapse a whole day or column at once',
      tr: 'Bir günü ya da kolonu tek seferde küçült',
      de: 'Einen ganzen Tag oder eine Spalte auf einmal einklappen',
      es: 'Contrae todo un día o una columna de una vez',
      fr: 'Réduis toute une journée ou une colonne d’un coup',
      hi: 'पूरे दिन या कॉलम को एक साथ छोटा करें',
      ru: 'Сворачивайте целый день или колонку одним нажатием',
      zh: '一键折叠整天或整列',
    },
    summary: {
      en: 'Calendar days and Kanban columns now have a button that collapses or expands every card inside them in one click.',
      tr: 'Takvim günlerinde ve Kanban kolonlarında artık içindeki tüm kartları tek tıkla küçültüp genişleten bir düğme var.',
      de: 'Kalendertage und Kanban-Spalten haben jetzt eine Schaltfläche, die alle Karten darin mit einem Klick ein- oder ausklappt.',
      es: 'Los días del Calendario y las columnas del Kanban ahora tienen un botón que contrae o expande todas sus tarjetas con un solo clic.',
      fr: 'Les journées du Calendrier et les colonnes du Kanban disposent désormais d’un bouton qui réduit ou développe toutes leurs cartes en un clic.',
      hi: 'कैलेंडर के दिनों और कानबन कॉलम में अब एक बटन है जो उनके अंदर के सभी कार्ड को एक ही क्लिक में छोटा या बड़ा कर देता है।',
      ru: 'У дней Календаря и колонок Канбана теперь есть кнопка, которая одним щелчком сворачивает или разворачивает все карточки внутри.',
      zh: '日历的每一天和看板的每一列现在都有一个按钮，一键即可折叠或展开其中的所有卡片。',
    },
  },
  {
    id: '2026-08-18-collapsed-card-accent-icon',
    date: '2026-08-18',
    category: 'improved',
    title: {
      en: 'Collapsed cards keep their icon',
      tr: 'Küçültülmüş kartlar ikonunu koruyor',
      de: 'Eingeklappte Karten behalten ihr Icon',
      es: 'Las tarjetas contraídas conservan su icono',
      fr: 'Les cartes réduites gardent leur icône',
      hi: 'छोटे किए कार्ड अपना आइकन बनाए रखते हैं',
      ru: 'Свёрнутые карточки сохраняют значок',
      zh: '折叠卡片保留其图标',
    },
    summary: {
      en: 'When you collapse a Calendar or Kanban card, its accent line now shows the selected option’s icon too, so you can still tell what it is at a glance.',
      tr: 'Bir Takvim ya da Kanban kartını küçülttüğünde, vurgu çizgisi artık seçili seçeneğin ikonunu da gösteriyor; kart küçükken bile neyi temsil ettiğini bir bakışta görebiliyorsun.',
      de: 'Wenn du eine Kalender- oder Kanban-Karte einklappst, zeigt ihre Akzentlinie jetzt auch das Icon der ausgewählten Option, damit du auf einen Blick erkennst, worum es geht.',
      es: 'Al contraer una tarjeta de Calendario o Kanban, su línea de acento ahora también muestra el icono de la opción seleccionada, así puedes reconocerla de un vistazo.',
      fr: 'Quand tu réduis une carte de Calendrier ou de Kanban, sa ligne d’accent affiche désormais aussi l’icône de l’option sélectionnée, pour la reconnaître d’un coup d’œil.',
      hi: 'जब आप किसी कैलेंडर या कानबन कार्ड को छोटा करते हैं, तो अब उसकी एक्सेंट लाइन पर चुने गए विकल्प का आइकन भी दिखता है, ताकि एक नज़र में पता चल सके कि वह क्या है।',
      ru: 'Когда вы сворачиваете карточку Календаря или Канбана, на её акцентной линии теперь также отображается значок выбранного варианта — сразу понятно, о чём карточка.',
      zh: '折叠日历或看板卡片时，强调线上现在也会显示所选项的图标，一眼就能看出这张卡片是什么。',
    },
  },
  {
    id: '2026-08-18-agent-repeating-tasks',
    date: '2026-08-18',
    category: 'new',
    title: {
      en: 'Agents can set up repeating tasks',
      tr: 'Ajanlar tekrarlayan görev kurabiliyor',
      de: 'Agenten können wiederkehrende Aufgaben anlegen',
      es: 'Los agentes pueden crear tareas periódicas',
      fr: 'Les agents peuvent créer des tâches récurrentes',
      hi: 'एजेंट दोहराने वाले कार्य बना सकते हैं',
      ru: 'Агенты могут создавать повторяющиеся задачи',
      zh: '智能体可以创建重复任务',
    },
    summary: {
      en: 'You can now just tell a connected AI agent to open a task every Monday and it sets the whole schedule up for you.',
      tr: 'Bağladığın yapay zekâ ajanına artık "her Pazartesi şu görevi aç" demen yetiyor, tekrarlama düzenini kendisi kuruyor.',
      de: 'Du kannst einem verbundenen KI-Agenten jetzt einfach sagen, er soll jeden Montag eine Aufgabe anlegen — den ganzen Rhythmus richtet er selbst ein.',
      es: 'Ahora basta con pedirle a un agente de IA conectado que abra una tarea cada lunes y él configura toda la periodicidad.',
      fr: 'Il suffit désormais de demander à un agent IA connecté d’ouvrir une tâche chaque lundi : il met en place toute la récurrence.',
      hi: 'अब आप जुड़े हुए AI एजेंट से बस इतना कह सकते हैं कि हर सोमवार एक कार्य खोले — वह पूरा दोहराव खुद सेट कर देता है।',
      ru: 'Теперь достаточно попросить подключённого ИИ-агента открывать задачу каждый понедельник — он сам настроит весь график.',
      zh: '现在你只需告诉已连接的 AI 智能体"每周一开一个任务"，它就会把整个重复计划设置好。',
    },
  },
  {
    id: '2026-08-18-recurring-calendar-tasks',
    date: '2026-08-18',
    category: 'new',
    title: {
      en: 'Repeating calendar tasks',
      tr: 'Tekrarlayan takvim görevleri',
      de: 'Wiederkehrende Kalenderaufgaben',
      es: 'Tareas de calendario periódicas',
      fr: 'Tâches de calendrier récurrentes',
      hi: 'दोहराने वाले कैलेंडर कार्य',
      ru: 'Повторяющиеся задачи в календаре',
      zh: '重复的日历任务',
    },
    summary: {
      en: 'Calendar cards can now repeat on any schedule you like, and when you change that schedule only the upcoming cards follow it — everything you already filled in stays exactly as it is.',
      tr: 'Takvim kartları artık istediğin düzende tekrarlanabiliyor ve düzeni değiştirdiğinde yalnızca sonraki kartlar ona uyuyor; içini doldurduğun kartlar olduğu gibi kalıyor.',
      de: 'Kalenderkarten lassen sich jetzt in jedem gewünschten Rhythmus wiederholen — änderst du den Rhythmus, folgen nur die kommenden Karten, alles bereits Ausgefüllte bleibt unangetastet.',
      es: 'Las tarjetas del calendario ya pueden repetirse con la frecuencia que quieras, y al cambiarla solo la siguen las tarjetas futuras: todo lo que ya rellenaste se queda igual.',
      fr: 'Les cartes du calendrier peuvent désormais se répéter au rythme de votre choix, et si vous changez ce rythme seules les cartes à venir le suivent — tout ce que vous avez déjà rempli reste intact.',
      hi: 'कैलेंडर कार्ड अब आपकी पसंद के किसी भी क्रम में दोहराए जा सकते हैं, और क्रम बदलने पर सिर्फ़ आगे के कार्ड बदलते हैं — जो आपने पहले भर दिया है वह वैसा ही रहता है।',
      ru: 'Карточки календаря теперь можно повторять с любым удобным ритмом, а при смене ритма меняются только будущие карточки — всё, что вы уже заполнили, остаётся как есть.',
      zh: '日历卡片现在可以按你喜欢的任意周期重复，改变周期时只有后续卡片会跟着变，你已经填好的内容原样保留。',
    },
  },
  {
    id: '2026-08-18-recurring-delete-scopes',
    date: '2026-08-18',
    category: 'new',
    title: {
      en: 'Choose how much of a series to delete',
      tr: 'Seride ne kadarını sileceğini seç',
      de: 'Wähle, wie viel einer Serie du löschst',
      es: 'Elige cuánto de una serie eliminar',
      fr: 'Choisissez ce que vous supprimez dans une série',
      hi: 'चुनें कि शृंखला का कितना हिस्सा हटाना है',
      ru: 'Выбирайте, какую часть серии удалить',
      zh: '自由选择要删除系列中的多少',
    },
    summary: {
      en: 'Deleting a repeating card now asks whether you mean just this one, this one and everything after it, or the whole series, and tells you up front how many cards already have content in them.',
      tr: 'Tekrarlayan bir kartı silerken artık yalnızca bu görevi mi, bundan sonrakileri mi yoksa tüm seriyi mi kastettiğin soruluyor ve kaç kartın içinin dolu olduğu önceden söyleniyor.',
      de: 'Beim Löschen einer wiederkehrenden Karte wirst du jetzt gefragt, ob du nur diese, diese und alle folgenden oder die ganze Serie meinst — inklusive Hinweis, wie viele Karten schon Inhalt haben.',
      es: 'Al eliminar una tarjeta periódica ahora se te pregunta si te refieres solo a esta, a esta y las siguientes o a toda la serie, y se te avisa cuántas tarjetas ya tienen contenido.',
      fr: 'Supprimer une carte récurrente vous demande maintenant si vous visez seulement celle-ci, celle-ci et les suivantes, ou toute la série, en indiquant d’emblée combien de cartes contiennent déjà du contenu.',
      hi: 'दोहराने वाला कार्ड हटाते समय अब पूछा जाता है कि आपका मतलब सिर्फ़ इसी से है, इससे और आगे वालों से, या पूरी शृंखला से — साथ ही बताया जाता है कि कितने कार्ड में पहले से सामग्री है।',
      ru: 'При удалении повторяющейся карточки теперь спрашивают, имеете ли вы в виду только её, её и все последующие или всю серию, и сразу показывают, сколько карточек уже заполнено.',
      zh: '删除重复卡片时，现在会先问你指的是仅这一张、这张及之后的全部，还是整个系列，并提前告诉你有多少张已经填了内容。',
    },
  },
  {
    id: '2026-08-18-whats-new',
    date: '2026-08-18',
    category: 'new',
    title: {
      en: "What's New panel",
      tr: 'Yenilikler paneli',
      de: 'Neuigkeiten-Panel',
      es: 'Panel de novedades',
      fr: 'Panneau Nouveautés',
      hi: 'नया क्या है पैनल',
      ru: 'Панель новинок',
      zh: '更新动态面板',
    },
    summary: {
      en: 'Every new Remnus feature now shows up in the What’s New panel in your sidebar, so you never miss an update.',
      tr: 'Remnus’a gelen her yeni özellik artık kenar çubuğundaki Yenilikler panelinde görünüyor, hiçbir güncellemeyi kaçırmıyorsun.',
      de: 'Jede neue Remnus-Funktion erscheint jetzt im Neuigkeiten-Panel in deiner Seitenleiste, damit du kein Update mehr verpasst.',
      es: 'Cada nueva función de Remnus aparece ahora en el panel de novedades de tu barra lateral, para que no te pierdas ninguna actualización.',
      fr: 'Chaque nouvelle fonctionnalité de Remnus apparaît désormais dans le panneau Nouveautés de votre barre latérale, pour ne rien manquer.',
      hi: 'Remnus की हर नई सुविधा अब आपके साइडबार के "नया क्या है" पैनल में दिखती है, ताकि कोई अपडेट छूटे नहीं।',
      ru: 'Каждая новая возможность Remnus теперь появляется на панели новинок в боковом меню, чтобы вы ничего не пропустили.',
      zh: '每项 Remnus 新功能现在都会显示在侧边栏的更新动态面板中，让你不会错过任何更新。',
    },
  },
  {
    id: '2026-08-17-card-collapse',
    date: '2026-08-17',
    category: 'improved',
    title: {
      en: 'Collapse busy cards',
      tr: 'Kartları küçültme',
      de: 'Karten einklappen',
      es: 'Contraer tarjetas',
      fr: 'Réduire les cartes',
      hi: 'कार्ड छोटा करें',
      ru: 'Сворачивание карточек',
      zh: '折叠卡片',
    },
    summary: {
      en: 'Shrink any calendar or board card down to just its title so a packed day still fits on one screen.',
      tr: 'Takvim ve pano kartlarını tek satıra küçültebiliyorsun, böylece yoğun bir gün bile tek ekrana sığıyor.',
      de: 'Verkleinere jede Kalender- oder Board-Karte auf ihren Titel, damit auch ein voller Tag auf einen Bildschirm passt.',
      es: 'Reduce cualquier tarjeta del calendario o del tablero a solo su título para que un día lleno quepa en una pantalla.',
      fr: 'Réduisez n’importe quelle carte du calendrier ou du tableau à son seul titre pour qu’une journée chargée tienne sur un écran.',
      hi: 'किसी भी कैलेंडर या बोर्ड कार्ड को सिर्फ़ शीर्षक तक छोटा करें, ताकि व्यस्त दिन भी एक ही स्क्रीन में दिखे।',
      ru: 'Сожмите любую карточку календаря или доски до одного заголовка, чтобы насыщенный день помещался на экране.',
      zh: '可将日历或看板卡片折叠为仅显示标题，让排满的一天也能一屏看完。',
    },
  },
  {
    id: '2026-08-17-drag-drop-position',
    date: '2026-08-17',
    category: 'improved',
    title: {
      en: 'Drop cards exactly where you want',
      tr: 'Kartı tam istediğin yere bırakma',
      de: 'Karten genau dort ablegen, wo du willst',
      es: 'Suelta las tarjetas justo donde quieras',
      fr: 'Déposez les cartes exactement où vous voulez',
      hi: 'कार्ड ठीक वहीं छोड़ें जहाँ चाहें',
      ru: 'Перетаскивайте карточки точно на место',
      zh: '把卡片放到你想要的位置',
    },
    summary: {
      en: 'Dragging a card into a day or a column now places it at the exact position you drop it, not at the end of the list.',
      tr: 'Bir kartı güne veya kolona sürüklediğinde artık listenin sonuna değil, tam bıraktığın sıraya yerleşiyor.',
      de: 'Wenn du eine Karte in einen Tag oder eine Spalte ziehst, landet sie jetzt genau an der Stelle, an der du sie loslässt, statt am Listenende.',
      es: 'Al arrastrar una tarjeta a un día o una columna, ahora se coloca justo donde la sueltas y no al final de la lista.',
      fr: 'En glissant une carte dans un jour ou une colonne, elle se place désormais exactement où vous la déposez, et non en fin de liste.',
      hi: 'किसी कार्ड को दिन या कॉलम में खींचने पर वह अब सूची के अंत में नहीं, बल्कि ठीक उसी जगह बैठता है जहाँ आप छोड़ते हैं।',
      ru: 'Перетащенная в день или колонку карточка теперь встаёт ровно туда, куда вы её отпустили, а не в конец списка.',
      zh: '将卡片拖到某一天或某一列时，它会停在你松手的确切位置，而不是列表末尾。',
    },
  },
  {
    id: '2026-08-17-faster-saves',
    date: '2026-08-17',
    category: 'improved',
    title: {
      en: 'Faster saves after a drag',
      tr: 'Sürükledikten sonra daha hızlı kaydetme',
      de: 'Schnelleres Speichern nach dem Ziehen',
      es: 'Guardado más rápido tras arrastrar',
      fr: 'Enregistrement plus rapide après un glisser-déposer',
      hi: 'खींचने के बाद तेज़ सेव',
      ru: 'Быстрое сохранение после перетаскивания',
      zh: '拖动后保存更快',
    },
    summary: {
      en: 'Moving a card in a large database now saves almost instantly, with a clear "saved" indicator when it lands.',
      tr: 'Büyük bir veritabanında kartı taşımak artık neredeyse anında kaydediliyor ve tamamlandığında net bir "kaydedildi" göstergesi çıkıyor.',
      de: 'Das Verschieben einer Karte in einer großen Datenbank wird jetzt fast sofort gespeichert – mit einer klaren „Gespeichert“-Anzeige.',
      es: 'Mover una tarjeta en una base de datos grande ahora se guarda casi al instante, con un indicador claro de "guardado".',
      fr: 'Déplacer une carte dans une grande base est désormais enregistré quasi instantanément, avec un indicateur « enregistré » explicite.',
      hi: 'बड़े डेटाबेस में कार्ड हिलाने पर अब लगभग तुरंत सेव होता है और साफ़ "सेव हुआ" संकेत दिखता है।',
      ru: 'Перемещение карточки в большой базе теперь сохраняется почти мгновенно, с понятным индикатором «сохранено».',
      zh: '在大型数据库中移动卡片几乎可以立即保存，并会显示明确的"已保存"提示。',
    },
  },
  {
    id: '2026-08-12-agent-guides',
    date: '2026-08-12',
    category: 'new',
    title: {
      en: 'New guides for working with agents',
      tr: 'Ajanlarla çalışma rehberleri',
      de: 'Neue Leitfäden für die Arbeit mit Agenten',
      es: 'Nuevas guías para trabajar con agentes',
      fr: 'Nouveaux guides pour travailler avec des agents',
      hi: 'एजेंट के साथ काम करने की नई गाइड',
      ru: 'Новые руководства по работе с агентами',
      zh: '与智能体协作的新指南',
    },
    summary: {
      en: 'Fresh guides on keeping your agent connection secure and on why AI agents forget your project are now live on the blog.',
      tr: 'Ajan bağlantını güvende tutma ve yapay zekâ ajanlarının projeni neden unuttuğu üzerine yeni rehberler blogda yayında.',
      de: 'Neue Leitfäden dazu, wie du deine Agentenverbindung absicherst und warum KI-Agenten dein Projekt vergessen, sind jetzt im Blog.',
      es: 'Ya están en el blog nuevas guías sobre cómo mantener segura la conexión de tus agentes y por qué los agentes de IA olvidan tu proyecto.',
      fr: 'De nouveaux guides sur la sécurisation de la connexion de vos agents et sur l’oubli du contexte par les agents IA sont en ligne sur le blog.',
      hi: 'एजेंट कनेक्शन सुरक्षित रखने और AI एजेंट आपका प्रोजेक्ट क्यों भूल जाते हैं, इस पर नई गाइड अब ब्लॉग पर हैं।',
      ru: 'В блоге появились новые руководства о безопасности подключения агентов и о том, почему ИИ-агенты забывают ваш проект.',
      zh: '博客上线了新指南：如何保障智能体连接安全，以及 AI 智能体为何会忘记你的项目。',
    },
  },
  {
    id: '2026-08-05-agent-batch-read',
    date: '2026-08-05',
    category: 'new',
    title: {
      en: 'Agents read many pages at once',
      tr: 'Ajanlar birçok sayfayı tek seferde okuyor',
      de: 'Agenten lesen viele Seiten auf einmal',
      es: 'Los agentes leen muchas páginas a la vez',
      fr: 'Les agents lisent plusieurs pages d’un coup',
      hi: 'एजेंट एक साथ कई पेज पढ़ते हैं',
      ru: 'Агенты читают много страниц сразу',
      zh: '智能体一次读取多个页面',
    },
    summary: {
      en: 'Connected AI agents can now pull a whole set of pages in a single step, so they answer noticeably faster.',
      tr: 'Bağladığın yapay zekâ ajanları artık bir grup sayfayı tek adımda çekebiliyor ve gözle görülür şekilde daha hızlı yanıt veriyor.',
      de: 'Verbundene KI-Agenten können jetzt einen ganzen Satz Seiten in einem Schritt abrufen und antworten dadurch merklich schneller.',
      es: 'Los agentes de IA conectados ya pueden traer un conjunto de páginas en un solo paso, así que responden mucho más rápido.',
      fr: 'Les agents IA connectés peuvent désormais récupérer tout un ensemble de pages en une seule étape, et répondent donc bien plus vite.',
      hi: 'जुड़े हुए AI एजेंट अब एक ही चरण में कई पेज ला सकते हैं, इसलिए वे साफ़ तौर पर तेज़ जवाब देते हैं।',
      ru: 'Подключённые ИИ-агенты теперь получают целый набор страниц за один шаг и отвечают заметно быстрее.',
      zh: '已连接的 AI 智能体现在可一次性获取整组页面，回答速度明显更快。',
    },
  },
  {
    id: '2026-08-04-context-packs',
    date: '2026-08-04',
    category: 'new',
    title: {
      en: 'Agents get the right context automatically',
      tr: 'Ajanlara doğru bağlam otomatik veriliyor',
      de: 'Agenten erhalten automatisch den richtigen Kontext',
      es: 'Los agentes reciben el contexto correcto automáticamente',
      fr: 'Les agents reçoivent automatiquement le bon contexte',
      hi: 'एजेंट को सही संदर्भ अपने आप मिलता है',
      ru: 'Агенты автоматически получают нужный контекст',
      zh: '智能体自动获得所需上下文',
    },
    summary: {
      en: 'When an agent starts a task, Remnus now gathers the related pages from your workspace and hands them over on its own.',
      tr: 'Bir ajan göreve başladığında Remnus artık çalışma alanındaki ilgili sayfaları kendisi toplayıp ona veriyor.',
      de: 'Wenn ein Agent eine Aufgabe startet, sammelt Remnus jetzt selbst die passenden Seiten aus deinem Workspace und übergibt sie.',
      es: 'Cuando un agente inicia una tarea, Remnus reúne por su cuenta las páginas relacionadas de tu espacio y se las entrega.',
      fr: 'Quand un agent démarre une tâche, Remnus rassemble désormais tout seul les pages liées de votre espace et les lui transmet.',
      hi: 'जब कोई एजेंट काम शुरू करता है, तो Remnus अब आपके वर्कस्पेस से संबंधित पेज खुद जुटाकर उसे दे देता है।',
      ru: 'Когда агент берётся за задачу, Remnus сам собирает связанные страницы вашего рабочего пространства и передаёт их ему.',
      zh: '当智能体开始一项任务时，Remnus 现在会自动汇集工作区中的相关页面并交给它。',
    },
  },
  {
    id: '2026-08-04-agent-connection-fix',
    date: '2026-08-04',
    category: 'fixed',
    title: {
      en: 'Steadier agent connection',
      tr: 'Daha kararlı ajan bağlantısı',
      de: 'Stabilere Agentenverbindung',
      es: 'Conexión de agentes más estable',
      fr: 'Connexion des agents plus stable',
      hi: 'ज़्यादा स्थिर एजेंट कनेक्शन',
      ru: 'Более стабильное подключение агентов',
      zh: '更稳定的智能体连接',
    },
    summary: {
      en: 'Agent connections no longer hang or ask you to sign in again and again.',
      tr: 'Ajan bağlantıları artık takılmıyor ve seni tekrar tekrar giriş yapmaya zorlamıyor.',
      de: 'Agentenverbindungen hängen nicht mehr und fordern dich nicht immer wieder zur Anmeldung auf.',
      es: 'Las conexiones de agentes ya no se quedan colgadas ni te piden iniciar sesión una y otra vez.',
      fr: 'Les connexions d’agents ne se bloquent plus et ne vous redemandent plus de vous reconnecter sans arrêt.',
      hi: 'एजेंट कनेक्शन अब अटकते नहीं हैं और बार-बार साइन इन करने को नहीं कहते।',
      ru: 'Подключения агентов больше не зависают и не просят входить снова и снова.',
      zh: '智能体连接不再卡住，也不会反复要求你重新登录。',
    },
  },
];

/** Falls back to English if a locale somehow slips through (e.g. a new locale added
 *  to routing before the entries were translated). */
export function localizedText(text: LocalizedText, locale: string): string {
  return text[locale as Locale] ?? text.en;
}

export function newestEntryId(): string {
  return CHANGELOG[0]?.id ?? '';
}

/**
 * How many entries the user has not seen yet.
 *
 * `lastSeenId` is the newest entry id they had already seen. Anything above it in
 * the array is unread. With no cookie (first visit, or an id we no longer ship) we
 * fall back to a short recency window instead of "everything", so a fresh account
 * sees "3 updates this week", not the entire product history.
 */
export function countUnseenEntries(
  lastSeenId: string | null | undefined,
  now: Date = new Date(),
): number {
  if (lastSeenId) {
    const index = CHANGELOG.findIndex((e) => e.id === lastSeenId);
    if (index !== -1) return index;
  }
  const cutoff = now.getTime() - FIRST_VISIT_WINDOW_DAYS * 86_400_000;
  return CHANGELOG.filter((e) => {
    const t = new Date(`${e.date}T00:00:00`).getTime();
    return !Number.isNaN(t) && t >= cutoff;
  }).length;
}
