// Generated by `npm run test:i18n-client -- --write` (src/scripts/test-i18n-client.ts).
// Do not edit by hand: the check fails when these drift from the code.
//
// The message namespaces each <ClientMessages scope> sends to the browser (V2 R9.1), on
// top of what its parent scope already sent. 'Ns.prefix*' = only the keys of Ns that
// start with prefix. root: the locale layout (every page); app: the signed-in shell;
// admin: (app)/admin; any other key: that public route directory under [locale].

export const CLIENT_NAMESPACES = {
  root: ['Billing', 'Consent', 'Errors', 'LanguageSwitcher', 'ProspectInvites', 'UI'],
  app: ['Comments', 'Dashboard', 'Database', 'DemoFeedback', 'Download', 'Editor', 'Graph', 'IconPicker', 'Landing.bridgePricing*', 'Layout', 'MobileNav', 'Onboarding', 'Page', 'Recurrence', 'Sharing', 'Templates', 'Updater', 'UserSettings', 'WhatsNew', 'Workspace', 'WorkspaceSettings'],
  admin: ['Admin', 'Mailing'],
  'client-login': ['Auth'],
  contact: ['Contact'],
  download: ['Download'],
  install: ['Install'],
  'landing-next': ['Download'],
  'landing-old': ['Download'],
  login: ['Auth'],
  oauth: ['OAuthAuthorize'],
  share: ['Database', 'Editor', 'Graph', 'IconPicker', 'Landing.bridgePricing*', 'Landing.nav*', 'Page', 'Sharing', 'Templates', 'Updater', 'UserSettings', 'Workspace', 'WorkspaceSettings'],
} as const;

export type ClientScope = Exclude<keyof typeof CLIENT_NAMESPACES, 'root'>;
